/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.urbanstreet2.view;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

import com.urbanstreet2.common.*;
import javax.swing.ImageIcon;
/**
 *
 * @author LAGV
 */
public class Login extends javax.swing.JFrame {

  
    /**
     * Creates new form login
     */
    public Login() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_User = new javax.swing.JTextField();
        txt_Pass = new javax.swing.JPasswordField();
        textoFondo1 = new javax.swing.JLabel();
        textoFondo2 = new javax.swing.JLabel();
        CustomFont cf = new CustomFont();
        cf.setFonts();
        lbl_User = new javax.swing.JLabel();
        lbl_Pass = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JLabel();
        new_Pass = new javax.swing.JLabel();
        back_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_User.setBorder(null);
        getContentPane().add(txt_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, 20));

        txt_Pass.setBorder(null);
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 260, 20));

        textoFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TEXTFIEL.png"))); // NOI18N
        getContentPane().add(textoFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 310, 40));

        textoFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TEXTFIEL.png"))); // NOI18N
        getContentPane().add(textoFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 310, 40));

        lbl_User.setFont(cf.getFont(1, 24f,1));
        lbl_User.setBackground(new java.awt.Color(185, 185, 185));
        lbl_User.setForeground(new java.awt.Color(185, 185, 185));
        lbl_User.setText("Usuario:");
        getContentPane().add(lbl_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbl_Pass.setFont(cf.getFont(1, 24f,1));
        lbl_Pass.setBackground(new java.awt.Color(185, 185, 185));
        lbl_Pass.setForeground(new java.awt.Color(185, 185, 185));
        lbl_Pass.setText("Contraseña:");
        getContentPane().add(lbl_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ACEPTARDES.png"))); // NOI18N
        btn_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_AceptarMouseReleased(evt);
            }
        });
        getContentPane().add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        new_Pass.setFont(cf.getFont(1, 18f,0));
        new_Pass.setForeground(new java.awt.Color(185, 185, 185));
        new_Pass.setText("Olvidé mi contraseña");
        new_Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_PassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_PassMouseExited(evt);
            }
        });
        getContentPane().add(new_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, -1));

        back_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/INICIAR SESION.png"))); // NOI18N
        getContentPane().add(back_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AceptarMouseEntered
        // TODO add your handling code here:
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../../images/ACEPTARSOBRE.png")));
    }//GEN-LAST:event_btn_AceptarMouseEntered

    private void btn_AceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AceptarMouseExited
        // TODO add your handling code here:
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../../images/ACEPTARDES.png")));
    }//GEN-LAST:event_btn_AceptarMouseExited

    private void btn_AceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AceptarMousePressed
        // TODO add your handling code here:
       btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../../images/ACEPTARPRES.png")));
    }//GEN-LAST:event_btn_AceptarMousePressed

    private void new_PassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_PassMouseEntered
        // TODO add your handling code here:
        Font font = new_Pass.getFont();
Map attributes = font.getAttributes();
attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
new_Pass.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_new_PassMouseEntered

    private void new_PassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_PassMouseExited
 Font font = new_Pass.getFont();
Map attributes = font.getAttributes();
attributes.put(TextAttribute.UNDERLINE, false);
new_Pass.setFont(font.deriveFont(attributes));        
    }//GEN-LAST:event_new_PassMouseExited

    private void btn_AceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AceptarMouseReleased
        // TODO add your handling code here:
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../../images/ACEPTARSOBRE.png")));
    }//GEN-LAST:event_btn_AceptarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_Image;
    private javax.swing.JLabel btn_Aceptar;
    private javax.swing.JLabel lbl_Pass;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JLabel new_Pass;
    private javax.swing.JLabel textoFondo1;
    private javax.swing.JLabel textoFondo2;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
